News_Portal/News_Portal/urls.py
from django.contrib import admin
from django.urls import path, include
from News_Portal_app.views import IndexView, CategoryList, subscribe
from django.contrib.auth.views import LogoutView
from News_Portal_app.views import upgrade_me


urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path('news/', include('News_Portal_app.urls')),
   path('articles/', include('News_Portal_app.urls_article')),
   path('accounts/', include('allauth.urls')),
   path('', IndexView.as_view()),
   path('logout/', LogoutView.as_view(template_name = 'logout.html'), name='logout'),
   path('upgrade/', upgrade_me, name = 'upgrade'),
   path('categories/<int:pk>', CategoryList.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

News_Portal/News_Portal_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse


class Author(models.Model):
    auth = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rate = models.IntegerField(default = 0)

    def update_rating(self):
        rating_of_post_by_author = self.post_set.all().aggregate(post_rating=Sum('post_rating'))['post_rating'] * 3
        rating_of_comments_by_author = self.auth.comment_set.all().aggregate(com_rating=Sum('com_rating'))['com_rating']
        rating_of_comments_to_author = Comment.objects.filter(post_com_id=self.id).aggregate(Sum('com_rating'))['com_rating__sum']
        self.author_rate = rating_of_post_by_author + rating_of_comments_by_author + rating_of_comments_to_author
        self.save()
        return self.author_rate


class Category(models.Model):
    sport = 'SP'
    politico = 'PO'
    education = 'ED'
    society = 'SO'
    technologies = 'TE'
    cat_field = [(sport, 'Cпорт'),
                 (politico, 'Политика'),
                 (education, 'Образование'),
                 (society, 'Общество'),
                 (technologies, 'Технологии')]

    cat_name = models.CharField(max_length=2, choices=cat_field, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, null=True, related_name='categories')

class Post(models.Model):
    article = 'AR'
    news = 'NE'
    cat_ar_ne = [(article, 'статья'),
                 (news, 'новость')]

    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    _type = models.CharField(max_length=2, choices=cat_ar_ne)
    time_in = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    heading = models.CharField(max_length=255)
    text = models.TextField()
    post_rating = models.IntegerField(default=0)

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
            self.post_rating -= 1
            self.save()

    def preview(self):
        return f'{self.text[0:124]}...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.heading.title()}: {self.text[:20]}'

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)

class Comment(models.Model):
    post_com = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    com_text = models.TextField()
    com_datetime = models.DateTimeField(auto_now_add=True)
    com_rating = models.IntegerField(default=0)

    def like(self):
        self.com_rating += 1
        self.save()

    def dislike(self):
        self.com_rating -= 1
        self.save()




News_Portal/News_Portal/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

News_Portal/News_Portal/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
<h1>Все новости и статьи</h1>
<h3>Сегодня {{ time_now|date:'d M Y' }}</h3>
<h3>Всего публикаций - {{ page_obj.paginator.count }}</h3>

{% if is_not_subscriber %}
<p class="text_center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
{% endif %}

{% if is_not_author %}
<button> <a href="upgrade/"> Стать автором!</a> </button>
{% endif %}

   <hr>
   {% if category_news_list %}
       <table>
           <tr>
               <td><h4>Заголовок</h4></td>
               <td><h4>Категория</h4></td>
               <td><h4>Дата публикации</h4></td>
               <td><h4>Текст статьи</h4></td>
           </tr>

           {% for post in category_news_list %}
           <tr>
               <td>{{ post.heading|truncatewords:2|censor }}</td>
               <td>
                   {% for category in post.categories.all %}
                   <a href="{% url 'category_list' category.id %}">{{ category.get_cat_name_display }}</a>
                   {% endfor %}
               </td>
               <td>{{ post.time_in|date:'M d Y' }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Упс, статей нет!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

News_Portal/News_Portal/templates/index.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>
<button> <a href="{% url 'post_list' %}"> Перейти на главную страницу</a> </button>
{% if is_not_author %}
<button> <a href="upgrade/"> Стать автором!</a> </button>
{% endif %}
<button> <a href="logout/">Выйти</a> </button>
{% endblock %}

News_Portal/News_Portal/templates/logout.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2> Вы вышли из системы </h2>
<button> <a href="{% url 'post_list' %}"> Перейти на главную страницу</a> </button>
{% endblock %}

News_Portal/News_Portal/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

News_Portal/News_Portal/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

News_Portal/News_Portal/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<!--h1>{{ post }}</h1-->
<h2>{{ post.heading|censor }}</h2>
<h4>{{ post.time_in|date:'d M Y' }}</h4>
<h5>{{ post.text|censor }}</h5>
<button> <a href="{% url 'post_list' %}"> Вернуться на главную страницу</a> </button>
{% endblock content %}

News_Portal/News_Portal/templates/post_created_emails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
<h2>Приветсвую! Новая <a href="{{ link }}">статья</a> в вашей подписке!</h>
  <p>{{ text }}</p>
</body>
</html>

News_Portal/News_Portal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление публикации</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.heading|truncatechars:20 }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

News_Portal/News_Portal/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
<h1>Все новости и статьи</h1>
<h3>Сегодня {{ time_now|date:'d M Y' }}</h3>
<h3>Всего публикаций - {{ page_obj.paginator.count }}</h3>

{% if is_not_author %}
<button> <a href="{% url 'upgrade' %}"> Стать автором!</a> </button>
{% endif %}
{% if not is_not_author %}
<button> <a href="{% url 'create_news' %}"> Добавить новость</a> </button>
<button> <a href="{% url 'create_article' %}"> Добавить статью</a> </button>
{% endif %}

   <hr>
   {% if posts %}
       <table>
           <tr>
               <td><h4>Заголовок</h4></td>
               <td><h4>Категории</h4></td>
               <td><h4>Дата публикации</h4></td>
               <td><h4>Текст статьи</h4></td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>
                   <a href="{% url 'post_detail' post.id %}">{{ post.heading|truncatewords:2|censor }}</a>
               </td>
               <td>
                   {% for category in post.categories.all %}
                   <a href="{% url 'category_list' category.id %}">{{ category.get_cat_name_display }}</a>
                   {% endfor %}
               </td>
               <td>{{ post.time_in|date:'M d Y' }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Упс, статей нет!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

News_Portal/News_Portal/templates/search_page.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}

<h3>Сегодня {{ time_now|date:'d M Y' }}</h3>
<h3>Найдено публикаций - {{ posts|length }}</h3>
<h1>Заполните поля для поиска публикаций</h1>

    {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

    <hr>
   {% if posts %}
       <table>
           <tr>
               <td><h4>Заголовок</h4></td>
               <td><h4>Дата публикации</h4></td>
               <td><h4>Текст статьи</h4></td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.heading|truncatewords:2|censor }}</td>
               <td>{{ post.time_in|date:'M d Y' }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Упс, статей нет!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

News_Portal/News_Portal/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1 class="text_center">{{ message }} <strong>{{ category }}</strong></h1>
<button> <a href="{% url 'post_list' %}"> Перейти на главную страницу</a> </button>
{% endblock %}

News_Portal/News_Portal/templates/weekly_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Новые статьи за прошедшую неделю</h2>
    <ul>
      {% for post in posts %}
      <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.heading }}</a></li>
      {% endfor %}
    </ul>
</body>
</html>